FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Запуск только интеграционных тестов
RUN CGO_ENABLED=0 GOOS=linux go test -c -o /bin/integration.test ./tests/integration

FROM alpine:3.23
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/integration.test /integration.test
CMD ["/integration.test", "-test.v"]
