run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - revive
    - lll

linters-settings:
  lll:
    line-length: 120

  revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
